FROM python:3.9-bullseye

ENV PYTHONUNBUFFERED 1

ARG ENVIRONMENT
ARG PINECONE_KEY
ARG OPENAI_KEY
ARG AUTH0_CLIENT_ID
ARG AUTH0_CLIENT_SECRET
ARG AWS_DEFAULT_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

ENV ENVIRONMENT=$ENVIRONMENT
ENV PINECONE_KEY=$PINECONE_KEY
ENV OPENAI_KEY=$OPENAI_KEY
ENV AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
ENV AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

ENV PYTHONPATH=/:$PYTHONPATH



WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app/ .

EXPOSE 80

# Run uvicorn when the container launches, adjust the module path as needed
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "80"]