Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref LogGroupName

  LogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref LogGroupName
      LogStreamName: !Ref LogStreamName

  LogGroupPolicy:
    Type: AWS::Logs::LogGroupPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs.amazonaws.com
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroupName}:*
      PolicyName: !Ref LogGroupPolicyName
      LogGroupName: !Ref LogGroupName

Outputs:
  LogGroupName:
    Value: !Ref LogGroupName
  LogStreamName:
    Value: !Ref LogStreamName