Parameters:
  ClusterName:
    Type: String
    Description: The name of the cluster.
  TaskFamily:
    Type: String
    Description: The family of the task definition.
  TaskCpu:
    Type: String
    Description: The CPU value for the task.
  TaskMemory:
    Type: String
    Description: The memory value for the task.
  TaskExecutionRoleArn:
    Type: String
    Description: The ARN of the task execution role.
  ContainerName:
    Type: String
    Description: The name of the container.
  ContainerImage:
    Type: String
    Description: The image of the container.
  ContainerPort:
    Type: Number
    Description: The port of the container.
  ServiceName:
    Type: String
    Description: The name of the service.
  DesiredCount:
    Type: Number
    Description: The desired count of the service.
  SecurityGroup:
    Type: String
    Description: The security group of the service.
  Subnet1:
    Type: String
    Description: The first subnet of the service.
  Subnet2:
    Type: String
    Description: The second subnet of the service.
  LogGroupName:
    Type: String
    Description: The name of the log group.


Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref TaskFamily
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref ContainerName

  Service:
    Type: AWS::ECS::Service
    DependsOn: TaskDefinition
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref SecurityGroup
          Subnets:
            - !Ref Subnet1
            - !Ref Subnet2

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref LogGroupName

Outputs:
  ServiceName:
    Description: The name of the created service.
    Value: !GetAtt Service.Name
