Parameters:
  LoadBalancerName:
    Type: String
    Description: The name of the load balancer.
  Subnet1:
    Type: String
    Description: The first subnet of the load balancer.
  Subnet2:
    Type: String
    Description: The second subnet of the load balancer.
  SecurityGroup:
    Type: String
    Description: The security group of the load balancer.
  CertificateArn:
    Type: String
    Description: The certificate ARN of the load balancer.
  TargetGroupName:
    Type: String
    Description: The target group name of the load balancer.
  ContainerPort:
    Type: Number
    Description: The port of the container.
  VpcId:
    Type: String
    Description: The VPC ID of the load balancer.
  DomainName:
    Type: String
    Description: The domain name of the load balancer.


Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref LoadBalancerName
      Scheme: internet-facing
      Type: application
      IpAddressType: ipv4
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Ref LoadBalancerName

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-2016-08
      Certificates:
        - CertificateArn: !Ref CertificateArn

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref TargetGroupName
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200
      Tags:
        - Key: Name
          Value: !Ref TargetGroupName

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: host-header
          Values:
            - !Ref DomainName
        - Field: path-pattern
          Values:
            - "/*"
      ListenerArn: !Ref Listener

Outputs:
  LoadBalancerDNSName:
    Value: !GetAtt LoadBalancer.DNSName