Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Ref DomainName

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt LoadBalancer.DNSName
        EvaluateTargetHealth: true
        HostedZoneId: !FindInMap [RegionMap, !Ref AWS::Region, ELBHostedZoneId]

Mappings:
  RegionMap:
    us-east-1:
      ELBHostedZoneId: Z35SXDOTRQ7X7K

Outputs:
  LoadBalancerDNSName:
    Value: !GetAtt LoadBalancer.DNSName