name: Destroy

on:
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "AsteriskChat"
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: chat-server
  CONFIG_DIRECTORY: ./ci

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Plan
        run: terraform plan

      - name: Validate
        run: terraform validate

      - name: Apply
        run: terraform apply

      - name: Destroy
        run: terraform destroy
